"""criar tabela condominios

Revision ID: 2d570975a20b
Revises:
Create Date: 2026-10-01 16:58:57.123597

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d570975a20b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "condominios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("cep", sa.String(length=8), nullable=True),
        sa.Column("logradouro", sa.String(length=200), nullable=True),
        sa.Column("bairro", sa.String(length=100), nullable=True),
        sa.Column("cidade", sa.String(length=100), nullable=True),
        sa.Column("uf", sa.String(length=2), nullable=True),
        sa.Column("sindico_nome", sa.String(length=200), nullable=True),
        sa.Column("sindico_email", sa.String(length=254), nullable=True),
        sa.Column("sindico_telefone", sa.String(length=11), nullable=True),
        sa.Column("contrato_inicio", sa.Date(), nullable=True),
        sa.Column("contrato_renovacao", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cnpj"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("condominios")
    # ### end Alembic commands ###
